[package]
name = "gen-random-desktop"
version = "0.2.0"
authors = ["cward"]
edition = "2018"

[dependencies]
requests = "0.0.*"
env_logger = "0.8.*"
log = "0.4.*"
structopt = "0.3.*"
eventual = "0.1.*"
